name: automation
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: Test-check
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |        
          # Your ML workflow goes here
          pip install -r requirements.txt
          python Test.py
          echo "end here !!!"
